### ISSUE TITLE
Extensive use of methods return various copies of classes instead of pointers

### ISSUE THREAD

**Issue by sirvelo** [liangqi/qtopencl#1]
I have just started to build QtOpenCL and the mandelbrot demo program.  There are several issues that needed to be resolved in order to get the mandelbrot program running on Windows.  I determined that because QCLProgram is copied from the various QCLContext::createProgramFrom\* and QCLContext::buildProgramFrom\* methods which within these methods would cause the invocation of the QCLProgram destructor upon their exit:

inline QCLProgram::~QCLProgram()
{
    if (m_id)
        clReleaseProgram(m_id);
}

This calls clReleaseProgram().  Thus, by the time the copy held by the mandelbrot demo program is destroyed it has already been released.

I believe anywhere the following OpenCL constructs are returned in methods, they should be by pointer not copied and therefore need to be dynamically constructed within the QtOpenCL library and not on stack:
- Memory objects
- Contexts
- Command Queues
- Programs
- Kernels
- Events

I have started the modification of your source-code baseline to implement this request and it fixes the crash upon exit.

Alternatively, QCLProgram class needs to have a private implementation that is referenced counted so when copies are made the clReleaseProgram() method is called only on the last remaining reference.  This approach in conjunction with changing methods that return copies of the above listed OpenCL constructs would probably be the best approach in refactoring the QtOpenCL module.

**Comment by liangqi** [comment]
Thanks for the interest on QtOpenCL, but it's only for Qt 4 and haven't updated since Jan. 2011.

This repo is just a fork and my only commit for trying to port it to Qt 5.

There is a blog about OpenCL and Qt 5/Qt Quick, http://blog.qt.io/blog/2015/04/20/qt-quick-with-the-power-of-opencl-on-embedded-linux-devices/ . Perhaps it's worth a read. ^_^.

**Comment by sirvelo** [comment]
Well Liang it seems your effort was very successful.  I have built with Qt 5.4.1 MSVC 2013 OpenGL 64-bit distribution and with a few modifications have both demos (mandelbrot and bezierpatch) and most examples running.  For a couple of demo applications that don't run, there appear to be some kernel arguments issues that need to be looked at and will do that at some point.  I also added initialization of the OpenCL context for sharing with an OpenGL context for Windows.

I have been building individual projects - opencl and openclgl libraries and the demo and examnple programs separately within QtCreator.  I have "hacked' the project files - for now - just to get something runnng.  I will try to get the project files back into some original form that appear to build within the source-code tree of a particular Qt distribution in order to build a proper QtOpenCL module.  That particular side is completely new to me but of great interest to learn.  I also have been playing around with OpenCL only since the beginning of this year.  I am very interested in GPU programming.  i have been developing applications using Qt for nearly 8 years now.  i think there will be a great need for the QtOpenCL module.  Are there any plans in the Qt road map for reviving this?  I thought that I would ask.  I haven't read the blog at the link you provided yet.

Are you aware of anyone actively using this code, modified in some way and who have branches available?  I found this repository as well: https://github.com/k0zmo/qt-opencl.git.  i actually had more success with your branch.  This effort has been a great learning experience as I have been learning about Qt module implementation, Qt's private implementation paradigm, "d-pointer" and "q-pointer", the associated macros, etc.  I would like to have a circle of collaborators to nurture my learning efforts and also become part of a open-source team developing the QtOpenCL module.

Thanks so much for your initial effort in porting to Qt 5.  Hope to collaborate with you in the future!

Best Regards,
Greg Schultz

**Comment by liangqi** [comment]
Here is a thread about QtOpenCL, http://lists.qt-project.org/pipermail/development/2013-June/011616.html . But I didn't see much effort on it.

If you really like it, the module, you could try to bring it back to Qt 5 in shape, and perhaps send a mail into mailing list and get some feedback. Good luck.

And I am not familiar with OpenCL too, just wanted to learn a bit.

If you need any other help about how to port it to Qt 5 or similar, just let me know.

**Comment by sirvelo** [comment]
Thanks for all the information so far!  I will certainly reach out to you if I have any questions on how to make QtOpenCL build as a proper Qt module.

Best Regards,
Greg Schultz
